"""empty message

Revision ID: 48c347d5e03b
Revises: 
Create Date: 2019-03-23 16:22:52.924368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c347d5e03b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('healthy_fact_one', sa.String(length=64), nullable=True),
    sa.Column('healthy_fact_two', sa.String(length=64), nullable=True),
    sa.Column('healthy_fact_three', sa.String(length=64), nullable=True),
    sa.Column('healthy_fact_four', sa.String(length=64), nullable=True),
    sa.Column('healthy_fact_five', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_category'), 'food', ['category'], unique=False)
    op.create_index(op.f('ix_food_healthy_fact_five'), 'food', ['healthy_fact_five'], unique=False)
    op.create_index(op.f('ix_food_healthy_fact_four'), 'food', ['healthy_fact_four'], unique=False)
    op.create_index(op.f('ix_food_healthy_fact_one'), 'food', ['healthy_fact_one'], unique=False)
    op.create_index(op.f('ix_food_healthy_fact_three'), 'food', ['healthy_fact_three'], unique=False)
    op.create_index(op.f('ix_food_healthy_fact_two'), 'food', ['healthy_fact_two'], unique=False)
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=False)
    op.create_table('gift_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'cost')
    )
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.String(length=64), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('food_item_one_id', sa.Integer(), nullable=False),
    sa.Column('food_item_two_id', sa.Integer(), nullable=False),
    sa.Column('food_item_three_id', sa.Integer(), nullable=False),
    sa.Column('food_item_four_id', sa.Integer(), nullable=False),
    sa.Column('food_item_five_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'cost', 'food_item_one_id', 'food_item_two_id', 'food_item_three_id', 'food_item_four_id', 'food_item_five_id')
    )
    op.create_index(op.f('ix_package_package_type'), 'package', ['package_type'], unique=False)
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('system_controller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_controller_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_name'), 'admin', ['name'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_icon'), 'ingredients', ['icon'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('system_controller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_controller_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'cost', 'completed')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('picture', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id', 'cost')
    )
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    op.create_index(op.f('ix_item_picture'), 'item', ['picture'], unique=False)
    op.create_index(op.f('ix_item_type'), 'item', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_type'), table_name='item')
    op.drop_index(op.f('ix_item_picture'), table_name='item')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_table('item')
    op.drop_table('order')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_icon'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_admin_name'), table_name='admin')
    op.drop_table('admin')
    op.drop_table('system')
    op.drop_index(op.f('ix_package_package_type'), table_name='package')
    op.drop_table('package')
    op.drop_table('gift_card')
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_index(op.f('ix_food_healthy_fact_two'), table_name='food')
    op.drop_index(op.f('ix_food_healthy_fact_three'), table_name='food')
    op.drop_index(op.f('ix_food_healthy_fact_one'), table_name='food')
    op.drop_index(op.f('ix_food_healthy_fact_four'), table_name='food')
    op.drop_index(op.f('ix_food_healthy_fact_five'), table_name='food')
    op.drop_index(op.f('ix_food_category'), table_name='food')
    op.drop_table('food')
    # ### end Alembic commands ###
