"""empty message

Revision ID: 8740a463b5bf
Revises: 
Create Date: 2019-05-01 17:01:21.687242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8740a463b5bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_name'), 'admin', ['name'], unique=False)
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('withInformation', sa.String(length=64), nullable=True),
    sa.Column('picturePath', sa.String(length=64), nullable=True),
    sa.Column('iconPath', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', 'cost')
    )
    op.create_index(op.f('ix_food_category'), 'food', ['category'], unique=False)
    op.create_index(op.f('ix_food_iconPath'), 'food', ['iconPath'], unique=False)
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=False)
    op.create_index(op.f('ix_food_picturePath'), 'food', ['picturePath'], unique=False)
    op.create_index(op.f('ix_food_withInformation'), 'food', ['withInformation'], unique=False)
    op.create_table('gift_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'cost')
    )
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.String(length=64), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('food_item_one_id', sa.Integer(), nullable=False),
    sa.Column('food_item_two_id', sa.Integer(), nullable=False),
    sa.Column('food_item_three_id', sa.Integer(), nullable=False),
    sa.Column('food_item_four_id', sa.Integer(), nullable=False),
    sa.Column('food_item_five_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'cost', 'food_item_one_id', 'food_item_two_id', 'food_item_three_id', 'food_item_four_id', 'food_item_five_id')
    )
    op.create_index(op.f('ix_package_package_type'), 'package', ['package_type'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('address_line_1', sa.String(length=64), nullable=True),
    sa.Column('address_line_2', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('zip_code', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('picture', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_address_line_1'), 'user', ['address_line_1'], unique=False)
    op.create_index(op.f('ix_user_address_line_2'), 'user', ['address_line_2'], unique=False)
    op.create_index(op.f('ix_user_city'), 'user', ['city'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    op.create_index(op.f('ix_user_picture'), 'user', ['picture'], unique=False)
    op.create_index(op.f('ix_user_state'), 'user', ['state'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_index(op.f('ix_user_zip_code'), 'user', ['zip_code'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('picture_path', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    op.create_index(op.f('ix_item_picture_path'), 'item', ['picture_path'], unique=False)
    op.create_index(op.f('ix_item_quantity'), 'item', ['quantity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_quantity'), table_name='item')
    op.drop_index(op.f('ix_item_picture_path'), table_name='item')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_table('item')
    op.drop_table('order')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_user_zip_code'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_state'), table_name='user')
    op.drop_index(op.f('ix_user_picture'), table_name='user')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_city'), table_name='user')
    op.drop_index(op.f('ix_user_address_line_2'), table_name='user')
    op.drop_index(op.f('ix_user_address_line_1'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_package_package_type'), table_name='package')
    op.drop_table('package')
    op.drop_table('gift_card')
    op.drop_index(op.f('ix_food_withInformation'), table_name='food')
    op.drop_index(op.f('ix_food_picturePath'), table_name='food')
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_index(op.f('ix_food_iconPath'), table_name='food')
    op.drop_index(op.f('ix_food_category'), table_name='food')
    op.drop_table('food')
    op.drop_index(op.f('ix_admin_name'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
